language: java

jdk:
  - oraclejdk9

install: mvn -f gson install -DskipTests=true
script: mvn -f gson test

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
